[package]
name = "rusty_raytracer"
version = "0.1.0"
authors = ["fkropfhamer <fabian.kropfhamer@sblum.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
